---
title: 'England Blanket Bog Model: predict from model'
output:
  html_notebook: default
---

## Packages 
```{r}
library(raster)
library(rgdal)

library(parallel)
library(doParallel)
```

## Load data
```{r}
# model
load("../data/models/Mrf3final.rds")
Model <- M.rf.3.final 
rm(M.rf.3.final)

#predictors


# Import environmental and topographic data
elev <- raster("../data/topo_env_data.tif", band = 1)
surf <- raster("../data/topo_env_data.tif", band = 2)
inflow <- raster("../data/topo_env_data.tif", band = 3)
outflow <- raster("../data/topo_env_data.tif", band = 4)
slope <- raster("../data/topo_env_data.tif", band = 5)
aspect <- raster("../data/topo_env_data.tif", band = 6)

# Import UKCP09 climate data
gdd_1960_90_ann <- raster("../data/ukcp09GriddedDataAnnPrepd.tif", band = 1)
gsl_1960_90_ann <- raster("../data/ukcp09GriddedDataAnnPrepd.tif", band = 2)
rain_1960_90_annual <- raster("../data/ukcp09GriddedDataAnnPrepd.tif", band = 3)
rain_daily_mean_1960_90_annual <- raster("../data/ukcp09GriddedDataAnnPrepd.tif", band = 4)
raindays_1mm_1960_90_annual <- raster("../data/ukcp09GriddedDataAnnPrepd.tif", band = 5)
raindays_10mm_1960_90_annual <- raster("../data/ukcp09GriddedDataAnnPrepd.tif", band = 6)
temp_mean_1960_90_annual <- raster("../data/ukcp09GriddedDataAnnPrepd.tif", band = 7)
temp_min_1960_90_annual <- raster("../data/ukcp09GriddedDataAnnPrepd.tif", band = 8)
temp_max_1960_90_annual <- raster("../data/ukcp09GriddedDataAnnPrepd.tif", band = 9)
```

## Prepare data

make a raster stack
```{r}
Model$coefnames

predictors <- stack(
  elev, surf, inflow, outflow, slope, aspect,
  gdd_1960_90_ann, gsl_1960_90_ann,
  rain_1960_90_annual, rain_daily_mean_1960_90_annual,
  raindays_1mm_1960_90_annual, raindays_10mm_1960_90_annual,
  temp_mean_1960_90_annual, temp_min_1960_90_annual, 
  temp_max_1960_90_annual
)

names(predictors) <- c("elev", "aspect", "slope", "outflow", "inflow", "surf", 
                       "gdd", "gsl", "rain_ann", "rain_daily", "raindays_10mm", 
                       "raindays_1mm", "temp_mean", "temp_min", "temp_max")
```

crop to training data extent

```{r}
#load observations to get extent
observationsSPDF <- readOGR(dsn = "../data/FEP_points/Catchment_FEP_OS_TrainingPoints_final_clean.shp", verbose = TRUE)
boundbox <- observationsSPDF@bbox; boundbox 

predictors <- raster::crop(x = predictors, y = boundbox)
```

## Predict outputs from predictors

```{r}
output <- raster::predict(predictors, Model, type="raw", progress="text")

writeRaster(x = output, filename = "../outputs/BlanketBogRFModel.tif")

plot(output)

```



