---
title: 'England Blanket Bog Model: run models'
output:
  html_notebook: default
---

model run = `r Sys.time()`

## Packages 
```{r}
library(raster)
library(rgdal)
library(randomForest)
library(caTools)
library(ggplot2)

library(caret)
library(parallel)
library(doParallel)
```

## Load data
```{r}
load(file = "../data/input.data.rds")
```

## Start Parallel Processing

```{r}
detectCores()
getDoParWorkers()
cl <- makeCluster(detectCores()-1)
registerDoParallel(cl)
getDoParName()
getDoParWorkers()
#registerDoSEQ() # to stop parallel processing
```

#### Make training and test set




```{r}
library(caret)
set.seed(123)
inTrain <- createDataPartition(y = input.data$bbog, 
                               p = .75, # The percentage of data in the training set
                               list = FALSE) # The format of the results

training <- input.data[inTrain,]
testing <- input.data[-inTrain,]
nrow(training); nrow(testing)
table(training$bbog)
table(testing$bbog)
```

#### run model
Need the latest version of caret from github to avoid known bug.
```{r}
M.rf.3 <- train(bbog ~ .,
                data=training, 
                method = "rf")

save(M.rf.3, file = "../data/models/Mrf3.rds")

M.rf.3
```
Tuning information: optimal number of trees at each split is 9


```{r}
plot(varImp(object= M.rf.3), main= "RF - Variable Importance")
```

### Predict from model

```{r}
#Predictions
predictions <- predict(object = M.rf.3, newdata = testing, type="raw")
table(predictions)

confusionMatrix(predictions, testing[,"bbog"])
```

### run final model

```{r}
# M.rf.3.final <- train(bbog ~ .,
#                 data = input.data, 
#                 method = "rf")
# 
# save(M.rf.3.final, file = "../data/models/Mrf3final.rds")

M.rf.3.final

M.rf.3.final$coefnames
```


