---
title: 'England Blanket Bog Model: Data Preparation: Observations using peat depth data'
output: html_notebook
---


## Packages 
```{r, include=FALSE}
library(raster)
library(rgdal)
library(tidyverse)
library(rgeos)
```


## Import data ----
```{r}
list.files(path = "../data", pattern = ".shp")

observationsSPDF <- readOGR(dsn = "../data/peat_depth_survey_data_noGPR.shp", verbose = TRUE)

# #prepare area to crop data to
# model.area <- readOGR(dsn = "../data/YD_pilot_boundary.shp")
# no_PHIBB <- readOGR(dsn = "../data/YD_pilot_no_PHIBB.shp")
```

have a look: 
```{r}
dim(observationsSPDF)
levels(observationsSPDF$PEATTYPE)
hist(observationsSPDF$PEAT_DEPTH)
table(observationsSPDF$PEATTYPE)
plot(observationsSPDF)
#plot(model.area, add = TRUE)

```



## Filter

```{r}
observations <- observationsSPDF
#crop to model area
#boundbox <- model.area@bbox
#observations <- raster::crop(x = observationsSPDF, y = boundbox)

names(observations)
#remove variables and include a new bbog variable
observations <- observations[,c("PEAT_DEPTH", "PEATTYPE")]
dim(observations)
table(observations$PEATTYPE)
plot(observations, pch = 4, cex = 0.1, col = "red")
#plot(model.area, add = TRUE)
```


## Create absences

don't need to do this



# Export

```{r}
writeOGR(obj = observations, dsn = "../data/peat_obs.shp", 
         driver = "ESRI Shapefile", 
         verbose = FALSE, layer = "observations")
```

