---
title: "England Peat Depth Model: Train models"
output: html_notebook
---

#Peat Depths: run models

## Packages 
```{r, include=FALSE}
library(raster)
library(rgdal)

library(randomForest)
library(Rborist)

library(caret)
library(parallel)
library(doParallel)
```

## Load data
```{r}
load(file = "../data/input.data.rds")

dim(input.data)
input.data <- input.data[which(is.na(input.data$elev) == FALSE),]
input.data <- input.data[complete.cases(input.data),]
dim(input.data)
```


## Start Parallel Processing
```{r}
detectCores()
getDoParWorkers()
cl <- makeCluster(detectCores()-1)
registerDoParallel(cl)
getDoParName()
getDoParWorkers()
#registerDoSEQ() # to stop parallel processing
```


## Make training and test sets

```{r}
set.seed(123)
inTrain <- createDataPartition(y = input.data$PEAT_DEPTH, 
                               p = .75, # The percentage of data in the training set
                               list = FALSE) # The format of the results

training <- input.data[inTrain,]
testing <- input.data[-inTrain,]
nrow(training); nrow(testing)
```

#### train model
Need the latest version of caret from github to avoid known bug.

set model parameters
```{r}
params <- trainControl(method = "cv", number = 10)
```

train linear model
```{r}
Mlm2a <- train(PEAT_DEPTH ~ ., 
              data = training, 
              method = "lm", 
              trControl = params,  
              metric = "Rsquared")

save(Mlm2a, file = "../data/models/Mlm2a.rds")

Mlm2a
```

train model
```{r}
Mrf2a <- train(PEAT_DEPTH ~ ., 
              data = training, 
              method = "Rborist")

save(Mrf2a, file = "../data/models/Mrf2a.rds")

Mrf2a
```